### ISSUE TITLE
utf-8 type criteria too strict

### ISSUE THREAD

**Issue by aczcoetzee** [midstar/pycstruct#11]
The `_CastXmlParser._fundamental_type_to_pcstruct_type()` method assumes **any** `char` array is _utf-8_ and this ultimately results in a `StringDef` type for the character array.

This may not always be the case - sometimes you may have arrays of normal unsigned 8-bit integers for example.

Consider changing the criteria such that only an array of `char` is assumed to be _utf-8_. This will result in arrays of `unsigned char` and `signed char` to be treated as arrays of `uint8` and `int8` respectively.

**Comment by midstar** [comment]
Good idea. I will have a look at this.

**Comment by midstar** [comment]
This feature request has now been implemented in pycstruct 0.5.0.
