### ISSUE TITLE
Reach data by attribute instead of string indexing

### ISSUE THREAD

**Issue by vallsv** [midstar/pycstruct#19]
Hi,

On my use case, i am dealing with huge data structure, and i only read them.

What about using attribute instead of string indexing to make it easier to read?

This way you also could reuse part of C code :-)

Here is common stuff i have to deal with:
```
        ss_cpu_all = sstat["cpu"]["all"]
        available_ticks = (
            ss_cpu_all["stime"]
            + ss_cpu_all["utime"]
            + ss_cpu_all["ntime"]
            + ss_cpu_all["itime"]
            + ss_cpu_all["wtime"]
            + ss_cpu_all["Itime"]
            + ss_cpu_all["Stime"]
            + ss_cpu_all["steal"]
            + ss_cpu_all["guest"]
        )
```
Which could be reached this way:
al with:
```
        all_cpu = sstat.cpu.all
        available_ticks = (
            all_cpu.stime
            + all_cpu.utime
            + all_cpu.ntime
            + all_cpu.itime
            + all_cpu.wtime
            + all_cpu.Itime
            + all_cpu.Stime
            + all_cpu.steal
            + all_cpu.guest
        )
```

I have no idea how the lib works internally, but could be done by specializing the returned dict from `deserialized`? Or use named tuples.

**Comment by midstar** [comment]
Hi,

I had a look at named tuples. Unfortunately these are immutable and therefore not very good for the use cases I'm personally using pycstruct for. You could always convert the returned dictionary to something that is accessible by attribute. I found following libraries https://github.com/bcj/AttrDict and https://github.com/makinacorpus/easydict.

**Comment by midstar** [comment]
Since the introduction of Instance type pycstruct do support access by attribute name. Therefore I suggest this ticket to be closed.

**Comment by vallsv** [comment]
Thanks.
Looks nice.
