### ISSUE TITLE
Data as memory view with numpy structured array

### ISSUE THREAD

**Issue by vallsv** [midstar/pycstruct#20]
Hi,

I am dealing with huge data structure (like 100KB the C-structure) on big files.

I was guessing how to speed up the reading.

Numpy provides structured arrays https://numpy.org/doc/stable/user/basics.rec.html, and as you only have to deal with C types it could maybe match your model.

This could provide a 0-copy and compact data in memory.

I will maybe try around.

**Comment by vallsv** [comment]
So i did play with that https://github.com/vallsv/pycstruct/tree/compute-numpy-dtype

Sounds like very interesting as it speed up by 5 my use case io+parsing.

3.8s instead of 17.5s

But as you can see in my tests the API is not exactly the same.
- There is array of array of struct
- No way to read utf-8, but only bytes
- I did the short way, no union, no bitfields

But there is probably ways to abstract it.

I have just added few `dtype` functions in your model. It is not much invasive. Let me know if you think you are interest in. Also creating `ArrayDef` and `UnionDef` in your model could be useful.

Else i think i will create a function on my side, converting your model to dtype. It's also fine to me.

**Comment by midstar** [comment]
Hi,

Structured arrays from numpy seems to be a promising way of improving the performance of pycstruct. I suggest we either add separate serialize/deserialize methods or an argument to the existing methods where data can be (de)serialized to from structured arrays (if the user has installed numpy). It's fine that there might be some limitations using this method for now. It might be something to fix in future.

If you are interested please continue your work and create a pull-request in my repo. Just be aware that I require 100% test coverage of the pycstruct.py file ;-) I'll also add you as a co-worker of the pycstruct library :-)

**Comment by midstar** [comment]
Hi again,

I have been thinking of how to improve performance. As long as you don't need to (de)serialize all data, i.e. only sub-sets of the elements are of interest, then we should add a specific pycstruct object/instance. Instead of (de)serialize all data only the element of interest needs to be (de)serialized. I will make some experiments tomorrow. I that case, numpy is not required, i.e. the pycstruct object/instance will behave similar to structured arrays.

**Comment by vallsv** [comment]
I think instead of dedicated desealize/deserialize, just what i do with a dtype function is enough.

It's not a big deal for numpy user, and personally i prefer this way.

```
cstruct_t = ...object from pycstruct...
array = numpy.frombuffer(data, dtype=cstruct_t.dtype())
```

It's also very nice, cause in the end, you dont need dependency to numpy cause the dtype can only be compound by basic python objects.

I will clean up my commits. Don't add me as co-author, i will probably not have time to maintain anything :-)

**Comment by midstar** [comment]
Thank you,

I will have a look at your pull request later. Also, I'm experimenting with implementing a pcstruct instance class that does more or less what numpy does. Also, this instance will support access by attribute (as you wrote in another ticket). I notify when I'm done.

**Comment by vallsv** [comment]
If you try to reach data only when it is requested, it will be faster, but probably not in the worst case, when you have to read everything. But anyway, i think a dedicated object as you plan to do (instead of a dict) is a very good idea.

I can try to do some benchmark if you like when your solution is ready.

BTW i have not yet asked you if you have a kind of dedicated use case for `pycstruct`, like a project you use it for? I am very interesting to use it to read binary file headers. I think it could help me to remove some boiler plate.

**Comment by midstar** [comment]
Hi, I have now implemented the Instance object. Checkout my branch: 
feature/pycstruct-instance

To create an instance:
definition = pycstruct.StructDef()
Add some elements, including lists and nested structs/bitfields.

instance = pycstruct.Instance(definition)

Now you can access the elements in instance like this:
instance.myFieldName = 5
instance.mySubStruct.subField = 2
etc...

The (de)serialization is done for each element individually. 

Work left to do is:
- Documentation/code comments
- I would like to add a method i StructDef and BitfieldDef where an instance could be created

I originally wrote the library for use at my work to:
- Communicate with an embedded c based software that use a proprietary binary interface
- Read and write data stored by the same software in proprietary binary data format 

I tried to find any good library for the purpose but none fulfilled the requirements I had. I have so far not seen any other library supporting nested structures.

**Comment by vallsv** [comment]
For single flat structure, the lib is also very useful, as the fields are named.

Your implementation sound cool.

**Comment by vallsv** [comment]
I saw that you have now an InstanceList too, but without factory, if i am not wrong.

Maybe you could use `numpy.frombuffer(buffer, dtype, count, offset)` arguments.

`pydstruct_t.deserialize(buffer, count=10)`

So what in this case you can return a `InstanceList` when count is set.

BTW, `frombuffer` also support count=-1, so what the size of the list is automatically found according to the size of the buffer.

**Comment by vallsv** [comment]
Before i was using this kind of boilerplate
```
            pstat_list_t = pycstruct.StructDef()
            pstat_list_t.add(pstat_t, "pstats", length=npresent)
            assert pstat_list_t.size() <= len(pstat)
            pstats = pstat_list_t.deserialize(pstat[: pstat_list_t.size()])
            return pstats["pstats"]
```
BTW this guy `pstat[: pstat_list_t.size()]` is also and extra mem copy.

**Comment by vallsv** [comment]
Hi, here is a benchmark with dict/instance/numpy.

- I have tested a struct with 16 uint32 (something not too small, and not too big)
- Y axis is the time it takes (lower is better)
- X axis is the % of the structure you need to read
- Dash line is the time to deserialize, and the plain line includes the time to read

![Capture d’écran de 2021-02-20 20-59-40](https://user-images.githubusercontent.com/7579321/108607435-cde23080-73c0-11eb-9196-46e4a10477ce.png)

So looking at crossing lines, if you need only few elements better to use the instances, if you need the whole content better to use the dict. Instance looks anyway promising, i am pretty sure there is things to fight against.

Here is my code: https://github.com/vallsv/pycstruct/blob/benchmark/benchmark.py

**Comment by midstar** [comment]
Thank you very much for this investigation. I will try to look at this today and get back.

**Comment by midstar** [comment]
Hi again,

I had a look at your performance test. My guess is that numpy structured arrays is implemented on lower level (c-code) and it will probably be impossible to get similar performance without doing the same for pycstruct.

Also, I checked your pull request regarding including dtype in pycstruct. I had a few comments but I'm willing to include this. It should, as you already have implemented it, be an alternative for those who wants have high performance for basic, non nested, structs. I don't want numpy to be a required dependency.

**Comment by vallsv** [comment]
Hi,

Yes, that's low level API that is why it is so fast.

But my point was there is way to speed up the instance implementation.

A did a test in https://github.com/vallsv/pycstruct/tree/benchmark, reducing dict indexing, and lazy initializing attributes. Test is not passing anymore for stuff like `instance.garage.cars[0].prop2 = 3`. I most probably don't understand anymore C very well. Anyway you can see in the following plot that the instance implementation is a bit faster, just in between the dict and the numpy impl.

![Capture d’écran de 2021-02-21 10-42-16](https://user-images.githubusercontent.com/7579321/108621334-6ebd0400-7432-11eb-8387-e0b927f5ba29.png)

Anyway any benchmark can be criticized.

**Comment by vallsv** [comment]
Thanks a lot.
I close this issue.
