### ISSUE TITLE
black / pytest

### ISSUE THREAD

**Issue by vallsv** [midstar/pycstruct#27]
Hi,

I would like to know if you would like to check this libs for your project?

I use this 2 libs for few years now and i really feel it help to work on a project with many people.

- `pytest` reduce a lot of boilerplate to write test (instead of `unittest`, no need `assertEqual`, no need extra classes). The good thing is it is compatible, so you can use `pytest` without changing anything of your tests right now
- `black` enforce a code-style formatting, so what there is no need to care about space, indentation, and empty lines

**Comment by midstar** [comment]
Hi,

I have been using pytest a lot previously for larger / more advanced projects. The reason why I did not use it here was that I did not require any features from it and tried to keep down the number dependencies for pycstruct.

black seems to be a nice package that I have never seen before. I have been thinking about using pylint also. I will definitely consider using black and pylint.

**Comment by midstar** [comment]
Hi again,

Thanks for the tip regarding black. It is great. I have "blacked" all python files in the repository and added a check in CI that files has been blacked prior push to origin.

Also, started using pylint. Only pycstruct and __init__ linted so far. Also with check in CI.

**Comment by vallsv** [comment]
Thanks. That's already much easier to share code.

About pytest again, i just can say that's a test dependency only. That's a dependency for your CI, and for devs, but it is not part of the project dependency anyway. So users don't have to deal with. So finally it's just a way to internally organize your code, with less verbosity on tests.

Anyway i close this issue. Thanks a lot.
